-- supabase/migrations/xxxxxxxx_create_transcriptions_table.sql

-- Criar a tabela para as transcrições
create table public.transcriptions (
    id bigint generated by default as identity primary key,
    title text null,
    content text null,
    created_at timestamp with time zone not null default now()
);

-- Ativar a Row Level Security (RLS) para a tabela
alter table public.transcriptions enable row level security;

-- Criar uma política que permite acesso total (leitura e escrita) a qualquer pessoa.
-- Para uma aplicação real, isto seria restrito a utilizadores autenticados.
create policy "Public access for MVP" on public.transcriptions
for all
using (true)
with check (true);