create table public.transcriptions (
    id bigint generated by default as identity primary key,
    title text null,
    content text null,
    created_at timestamp with time zone not null default now()
);

alter table public.transcriptions enable row level security;

create policy "Public access for MVP" on public.transcriptions
for all
using (true)
with check (true);